spring:
  application:
    name: user-service
server:
  port: 0
logging:
  level:
    root: info
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN
eureka:
  client:
    serviceUrl:
      defaultZone: http://182.254.192.61:8761/eureka/